language: cpp
compiler: 
  - gcc
  - clang
os: 
  - linux
  - osx
install: 
  - ./autogen.sh
  - ./configure
  - make
  - make check
before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then sudo apt-get install autoconf automake libtool fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then sudo brew install autoconf automake libtool fi
  - git clone https://github.com/Kinetic/kinetic-java
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
  - echo $JAVA_HOME
  - mvn -f ./kinetic-java/pom.xml -DskipTests clean package 
  - ./kinetic-java/bin/startSimulator.sh &
  - sleep 10
script: 
  - ./kinetic_client_test
  - ./kinetic_integration_test
